# NOTE: This would need to be in the root of the repo to use it
# I placed it here because it is associated with this video

name: Lint Code Base

on: push

env: # Comment env block if you don't want to apply fixes
  # Apply linter fixes configuration
  APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unittest
        run: python3 -m unittest acm_planner/network/test_networks.py
      
      - name: Lint Code Base
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: false
          auto_fix: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}