# NOTE: This would need to be in the root of the repo to use it
# I placed it here because it is associated with this video

name: Lint Code Base

on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unittest
        run: python3 -m unittest acm_planner/network/test_networks.py
      
      - name: Lint Code Base
        uses: samuelmeuli/lint-action@v1
        with:
            github_token: ${{ secrets.github_token }}
            black: true
            flake8: true
        # env:
        #   VALIDATE_ALL_CODEBASE: false
        #   auto_fix: true
        #   DEFAULT_BRANCH: main
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}